### ISSUE TITLE
STT0048: Training stt whisper model.

### ISSUE THREAD

**Issue by gangagyatso4364** [spsither/stt-whisper#1]
### Description
We need to train stt-whisper model on the new datasets that we have gained, also because of the new departments data introduced.

### Completion Criteria
Stt whisper model with better performance and ready to be deployed. 

### Subtask
- [ ] prepare the dataset from training, validation, and benchmark dataset.
- [ ] get an estimation of training time and cost of training whisper model. 
- [ ] train the whisper model.
- [ ] evaluate the whisper model on benchmark dataset.
- [ ] push to hugging face.
