### ISSUE TITLE
STT0075: get the estimation of time and cost for training a whisper model.

### ISSUE THREAD

**Issue by gangagyatso4364** [spsither/stt-whisper#2]
### Description 
we are going to get an estimation of time and cost for training the whisper model. the whisper model is previously trained on 500 hours of training data but now we have 1500 hours training data so there will be significant improvement in this model compared to last time. 

[whisper paper](https://cdn.openai.com/papers/whisper.pdf)
[whisper base model code](https://github.com/openai/whisper)
[whisper  paper vedio](https://www.youtube.com/watch?v=AwJf8aQfChE&t=1825s)

### Completion Criteria 
A detailed estimation of time and cost and the GPU types used for training the stt-whisper model.

### Implementaion
1. Read whisper research paper and understand the architecture of the whisper model.
1. clone the stt-whisper repo in GCP and set up the environment.
2. create a mount and transfer the audio segment data from wadwani cloud s3 wav16k storage.
3. run prepare dataset
4. train whisper
5. do hullacination prevention in whisper model.
6. get estimation of time and cost. 

### Subtask 
- [x] understanding the whisper model architecture model from the paper.
- [x] set up the gcp environment with mount and stt-whisper repo
- [x] transfer the audio segments from cloud to my mounted volume
- [x] create train and validation excluding the benchmark
- [x] run the prepare dataset 
- [x] train the whisper model to get time estimation
- [x] get time and cost estimation.

**Comment by gangagyatso4364** [comment]
whisper small training on 1500 hours latest training data with new departments compared to 500 hours previously trained limited data variation in training. So we expect a better wer and cer score this time with more training data and variations in training data. 

time and spec:
epoch: 10
training data hours: 1500
4 (L4) 24 Gpu for 10 days or
8 (L4) 24 Gpu for 10 days
